# Setup
title: 小凯
description: 锦瑟无端五十弦，一弦一柱思华年
url: http://blogxiaokai.top
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpg
excerpt_separator: ""

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# # Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
# logo: logo.png
# social:
#   name: Songzi Vong
#   links:
#     - https://twitter.com/vszhub
#     - https://github.com/vszhub
# google_site_verification: xxxxx
# lang: zh

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: cj_kai
  url: https://github.com/111happy
  email: ch_kaijack@outlook.com
